### PR TITLE
I18n using Locale::TextDomain

### PR DESCRIPTION
**Pull request by sschober**
German translation files supplied

### CODE REVIEW

**Comment by sschober** [comment]
I've extended the localization a bit to incorporate parameter type documentation strings and posted a question on [stackoverflow](http://stackoverflow.com/questions/29749855/how-to-localize-cpan-module-and-dependencies) about your concern.

**Comment by celogeek** [comment]
Well, it isn't better to catch errors in your program and purpose a translation for them ?
The problem in perl library is that no body has intend to purpose an easy way to activate translation for their library.

**Comment by sschober** [comment]
I'm sorry, but I do not understand your last comment. Localization is activated simply by setting a different locale, but I'm sure you already know that... So, maybe you meant that no, or at least not every project owner/developer has time or intention to incorporate localization features into his/her project?

So, do you see it as a show stopper (i.e. no merge is happening until this issue is resolved), that messages not originating from `MooX::Options` are not translated yet? Maybe a step-by-step approach (i.e. merging this know and adding and mending to it over time) is a viable option?

**Comment by celogeek** [comment]
yeah, of course we need to go with one version.

Can  you rebase your branch on devel, and reduce the number of commit ?

I will merge it after that.

**Comment by celogeek** [comment]
We load module if it is very necessary. So you may use required for translation instead of use. Checkout the "croak" part.

**Comment by sschober** [comment]
Ok, I'll squash the commits. :)

> We load module if it is very necessary. So you may use required for translation instead of use. Checkout the "croak" part.

It seems neccessary to `use` `Locale::TextDomain` (see first sentence of [USAGE](http://search.cpan.org/~guido/libintl-perl-1.24/lib/Locale/TextDomain.pm#USAGE)).

**Comment by celogeek** [comment]
Of course no probleme. But only when you need it.

Something like :

sub _x {
require Locale::TextDomain;
goto &Locale::Text::Domain::_x
}

Or something like that.

**Comment by sschober** [comment]
d2e84e0 implements on-demand loading of `Locale::TextDomain` as you proposed, but the `format_doc` hash definition (see [here](https://github.com/sschober/MooX-Options/blob/d2e84e020334ea41c296c0a9b91ea5c77f3023e2/lib/MooX/Options/Descriptive/Usage.pm#L47) pulls it in every time. :/ 

Any idea how to circumvent this?

**Comment by sschober** [comment]
Rebased my `master` branch on your `devel` branch.

**Comment by sschober** [comment]
I've wrapped the doc string hashes pulling in `Locale::TextDomain` in functions but `MooX::Options::Role::parse_options` constructs the usage string every time it is called, even when it is not needed... so the module is still pulled in.

**Comment by celogeek** [comment]
Yeah, the only way to not used the Local::TextDomain is that the program actually works ;) any error or help message will need the load of Local::TextDomain.

Ok let the branch like this, I will take a look.

**Comment by celogeek** [comment]
About this :

```
-my %format_doc = (
-    's'  => 'String',
-    's@' => '[Strings]',
-    'i'  => 'Int',
-    'i@' => '[Ints]',
-    'o'  => 'Ext. Int',
-    'o@' => '[Ext. Ints]',
-    'f'  => 'Real',
-    'f@' => '[Reals]',
-);
+sub _format_doc {
+  my $format = shift;
+  my %format_doc = (
+      's'  => __("String"),
+      's@' => __("[Strings]"),
+      'i'  => __("Int"),
+      'i@' => __("[Ints]"),
+      'o'  => __("Ext. Int"),
+      'o@' => __("[Ext. Ints]"),
+      'f'  => __("Real"),
+      'f@' => __("[Reals]"),
+  );
+  return $format_doc{$format};
+}
```

I would suggest to keep the original hash, but inside the method or at the place you use it, call the translated version.
Like this :

```
__($format_long_doc{$format})
```

I suppose you use this way, because you have a generator or something.

Can't we create a comment, for this ?

**Comment by celogeek** [comment]
Also, a last thing, the sub you declare "__" and "_x", can't we have it somewhere ? only once ?
Like inside a role ?

Just to be sure, can you create a tiny tool.pl, and use "warn" or something, to see if we go inside the method everytime or only to display help message.

Because may be we can have a real "use" in the Descriptive module, and a load on demand in the MooX::Options;

That depend if we always need it when we call the Descriptive module or not. I'm pretty sure if we call it, it is to display a help message, and only here the textdomain is mandatory.

**Comment by celogeek** [comment]
for the format stuff. if we are force to describe all option with __, then create a "$format_doc" vars, and inside the method, "if (!defined $format_doc) { $format_doc = { __ ... } }"

**Comment by celogeek** [comment]
I'm reviewing it now. I will merge the result soon.

**Comment by celogeek** [comment]
Hi, I have create this branch with your merge, and a few fix from me :

redmine-feature-487-translate-using-locale-textdomain-sschober

Can you reset your branch on this one ?

Finally I have directly "use" the module, because it is used almost all the time, and it is slower to load it on demand.

I need several information inside the doc.

First, how do you regenerate the "po" file ? I have fix one string, and I don't know how to automatically fix the PO.

Also, why de we have 2 "de" po file. It should be en.pot and DE.po or something like that.

Can you add doc on "how to propose a translation ?" in MooX::Options ?

Thanks,

**Comment by sschober** [comment]
Ok, I've rebase on `redmine-feature-487-translate-using-locale-textdomain-sschober` and documentation to `README.mkdn`. I hope, I addressed all your questions in the text.

**Comment by celogeek** [comment]
Hi,

I try to look at it, but it seems you miss a "git push -f" of your branch.

Please don't change the README.mkdn, it is autogenerated. The doc is inside MooX::Options pod.

Add a "=head1 Translation" with explanation on how to contribute.

I will try to figure out how to do it myself in the meantime.

**Comment by celogeek** [comment]
OMG, ok the dzil contain the command !

I should be able to release now

**Comment by celogeek** [comment]
merged into devel !

**Pull request closed without merging**
