### PR TITLE
Reduce runtime dependency footprint

### PR DESCRIPTION
**Pull request by arc**
Several of the features in `MooX::Options` use extra modules. These changes delay loading such modules until they're actually needed. This reduces the runtime for `perl -we "require MooX::Options; require MooX::Options::Role"` from ~110 ms to ~45 ms on my machine.

There are also two other changes here:

* Use `like` in tests, to improve diagnostics
* Use `JSON::MaybeXS` instead of `JSON`, so that users with a fast XS-based JSON-decoding implementation can transparently use that instead

### CODE REVIEW

**Comment by celogeek** [comment]
Hi, thanks for the patch.

I have several question. For exemple in the "autosplit" loop, we do a require. does that mean we repeat the "import" each iteration ?

when you change "use" by "require", I'm not sure dist zilla still detect the dependancies.

I think is it a good idea to reduce the load time at minimum, but not to remove or break feature if you don't have the dependencies ready.

**Comment by arc** [comment]
Hi — those are all reasonable questions :-)

For autosplit: I've added an extra commit d7a2a51 that moves the `import` call out of the loop, with a comment explaining what's going on. (Let me know if you'd prefer this commit squashed into 4e21a81.)

Dist::Zilla dependency detection: I did `dzil build` on the tip of the tree after my changes, and diffed the generated META.yml against the version in the 4.018 release. As expected, the only changes to the dependencies were:

```diff
@@ -36,8 +36,7 @@
   Data::Record: '0'
   Getopt::Long: '2.43'
   Getopt::Long::Descriptive: '0.099'
-  JSON: '0'
-  MRO::Compat: '0'
+  JSON::MaybeXS: '0'
   Module::Metadata: '1.000019'
   Moo: '1.003001'
   MooX::ConfigFromFile: '0'
```

However, loading `Path::Class` at runtime does mean that the required version number is now specified in `dist.ini` rather than in the code; is that a problem?

**Comment by celogeek** [comment]
Hi, no it is fine, except it doesn't enforce the version.

For exemple if I require path class > X, and I have already have a Y version < X. It try to install a greater version, and if it fail, it continue and try to install the MooX::Options.
Because they is a use Path::Class X, the compile test fail, and it doesn't try to install MooX::Options with the missing deps.
If it is in the dist ini, and you install without test, it will succeed even if it has not the minimum version required, and then may crash during using.
The user will have hard time to find out why.

Also, can you do some changes,

For exemple you use "required Carp; croak ...." several time.
Can you change it into a "sub croak { use_module("Carp"); croak ... ?}
Well I thing use_module will only load once the module, if it is already in the $INC it skip.

May be create a role to do it, with :

the json encode, croak, ... anything that need to be load on demand.

**Comment by arc** [comment]
Hi. I've pushed a further commit that extracts a "sub croak" as you suggest. (However, it doesn't use `use_module()` from `Module::Runtime`, because I can't see any reason why just calling the `require` builtin wouldn't work.)

I'm rather doubtful that factoring out the other uses of runtime `require` would have any benefits. Could you maybe suggest what sort of thing you had in mind?

I've also pushed a commit that explicitly enforces the `Path::Class` version at runtime. (This doesn't change the dependency information in the META.yml generated by `dzil build`.)

Again, let me know if you'd like me to build a rebased version of this PR that squashes these commits into the corresponding earlier ones.

Thanks.

**Comment by celogeek** [comment]
merged into devel
thanks.

**Pull request closed without merging**
